spring:
    profiles:
        active: dev
    application:
        name: "FireSystem"
        version: "0.1"
---
spring:
    config:
        activate:
            on profile: dev
server:
    port: 8080
---
spring:
    config:
        activate:
            on profile: production
server:
    port: 9001
---
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/firesystem
        username: postgres
        password: postgresql
        diver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update