spring:
    profiles:
        active: dev
    application:
        name: "FireSystem"
        version: "0.1"
---
spring:
    config:
        activate:
            on profile: dev
server:
    port: 8080
---
spring:
    config:
        activate:
            on profile: production
server:
    port: 9001
---
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/firesystem
        username: postgres
        password: postgresql
        diver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        open-in-view: false
    mvc:
        static-path-pattern: /**

jwt:
  secret: "n8hkFK8e17SpmXpdeLJVn2NVUxt4NmCiEtnnMFsLB4C"
  access:
    duration:
      minute: 5
      second: 300
    cookie-name: access-token
  refresh:
    duration:
      day: 7
      second: 604800
    cookie-name: refresh-token

logging:
  level:
    org.springframework.security: DEBUG