spring:
    profiles:
        active: dev
    application:
        name: "FireSystem"
        version: "0.1"
---
spring:
    config:
        activate:
            on profile: dev
server:
    port: 8080
---
spring:
    config:
        activate:
            on profile: production
server:
    port: 9001
---
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/firesystem
        username: postgres
        password: postgresql
        diver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update

jwt:
  secret: "myVerySecretKey123456789012345678901234567890" # <-- ЗАМЕНИ НА СВОЙ КЛЮЧ, лучше сгенерированный
  access:
    duration:
      minute: 5
      second: 300
    cookie-name: access-token
  refresh:
    duration:
      day: 7
      second: 604800
    cookie-name: refresh-token